### ISSUE TITLE
MulJam dataset

### ISSUE THREAD

**Issue by groadabike** [zhuole1025/LyricWhiz#1]
Hi,
Is it possible to get access to MulJam dataset?
Is not available in MARBEL, yet.

Thank you
Gerardo

**Comment by jhuang448** [comment]
I have responded to the issue in the MARBLE repo: [https://github.com/a43992899/MARBLE-Benchmark/issues/13#issuecomment-1917630474](https://github.com/a43992899/MARBLE-Benchmark/issues/13#issuecomment-1917630474). I will close this one.
